baseURL = 'https://dirtym0nk.github.io/'
title = '–ú–æ–π –ë–ª–æ–≥'
theme = 'PaperMod'

# –Ø–∑—ã–∫–æ–≤—ã–µ –Ω–∞—Å—Ç—Ä–æ–π–∫–∏
defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = false  # –†—É—Å—Å–∫–∏–π –≤ –∫–æ—Ä–Ω–µ /

[languages]
  [languages.ru]
    languageCode = 'ru-RU'
    languageName = '–†—É—Å—Å–∫–∏–π'
    weight = 1
    
    [languages.ru.params]
      homeInfoParams.Title = "–ü—Ä–∏–≤–µ—Ç üëã"
      homeInfoParams.Content = "–≠—Ç–æ –º–æ–π –ª–∏—á–Ω—ã–π –±–ª–æ–≥"
    
    [[languages.ru.menu.main]]
      name = "–ê—Ä—Ö–∏–≤"
      url = "/archives/"
      weight = 10
    [[languages.ru.menu.main]]
      name = "–¢–µ–≥–∏"
      url = "/tags/"
      weight = 20

  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 2
    
    [languages.en.params]
      homeInfoParams.Title = "Hello üëã"
      homeInfoParams.Content = "This is my personal blog"
    
    [[languages.en.menu.main]]
      name = "Archive"
      url = "/en/archives/"
      weight = 10
    [[languages.en.menu.main]]
      name = "Tags"
      url = "/en/tags/"
      weight = 20

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  defaultTheme = "auto"
  displayFullLangName = false  # –ü–æ–∫–∞–∑—ã–≤–∞–µ—Ç "RU" / "EN" –≤–º–µ—Å—Ç–æ –ø–æ–ª–Ω—ã—Ö –Ω–∞–∑–≤–∞–Ω–∏–π

